# Build script for filesystem core sources.
#
# (C) 2017 KATO Takeshi
#

NAME = 'core_fs'

CORE_FS_SOURCES = [
 'fs_ctl.cc',
 'name_ops.cc',
 'path_parser.cc',
 'sys_fs.cc',
]

def configure(x):
	x.env.append_value('KERNEL_LINK_USE', NAME)

def build(x):
	x.objects(
	    target   = NAME,
	    source   = CORE_FS_SOURCES,
	    use      = 'KERNEL',
	)

