#
# (C) 2014 KATO Takeshi
#


ramfs_name = 'ramfs'

def configure(x):
	if x.env['CONFIG_RAMFS']:
		x.env.append_value('KERNEL_LINK_USE', ramfs_name)

def build(x):
	if x.env['CONFIG_RAMFS']:
		x.objects(
		    target   = ramfs_name,
		    source   = 'ramfs.cc',
		    use      = ['KERNEL'],
		)

