# Build script of filesystem driver.
#
# (C) 2014 KATO Takeshi
#


name = 'fs_drivers'


def configure(x):
	x.env.append_value('KERNEL_LINK_USE', name)


def build(x):
	sources = ['devfs.cc']

	sources.append('ramfs.cc')

	x.objects(
		target   = name,
		source   = sources,
		use      = ['KERNEL'],
	)

