# @brief  first process
#
# (C) 2014 KATO Takeshi
#


source = [
    'main.cc',
    'start.S',
    'syscall.S',
]


def build(x):
    target = x.path.find_or_declare('first')
    x.program(
        features      = 'asm cxxprogram linker_opts',
        target        = target,
        source        = source,
        linkflags     = ['-nostdlib'],
        linker_script = 'first.lds',
        mapfile       = 'first.map')

