#
# (C) 2011-2013 KATO Takeshi
#


def configure(x):
	if x.env.CONFIG_MULTIBOOT or x.env.CONFIG_MULTIBOOT2:
		x.recurse('multiboot')

def build(x):
	if x.env.boot_fd:
		x.recurse('fd')

	if x.env.CONFIG_MULTIBOOT or x.env.CONFIG_MULTIBOOT2:
		x.recurse('multiboot')
