#
# (C) 2011-2012 KATO Takeshi
#


def options(x):
	debug_opt = x.get_option_group('debug options')

def configure(x):
	if x.env.boot_multiboot:
		x.recurse('multiboot')

def build(x):
	if x.env.boot_fd:
		x.recurse('fd')

	if x.env.boot_multiboot:
		x.recurse('multiboot')
