# architecture independent kernel codes.
#
# (C) 2011 KATO Takeshi
#


kern_sources = [
    'drive.cc',
    'fileif.cc',
    'interrupt_control.cc',
    'log.cc',
    'log_access.cc',
    'slab_allocate.cc',
    'string.cc',
]

kern_defines = []


setup_sources = [
    'log.cc',
    'string.cc',
]

setup_defines = []


def build(x):
	kern_defines.extend(x.env.common_defines)
	setup_defines.extend(x.env.common_defines)

	x.objects(
	    target   = 'kernel_objs',
	    source   = kern_sources,
	    defines  = kern_defines,
	    use      = 'KERNEL'
	)

	x.objects(
	    target   = 'setup_objs',
	    source   = setup_sources,
	    defines  = setup_defines,
	    use      = 'SETUP'
	)

