# architecture independent kernel codes.
#
# (C) 2011 KATO Takeshi
#


kern_sources = [
    'cpu.cc',
    'drive.cc',
    'file.cc',
    'interrupt_control.cc',
    'kern_log.cc',
    'log_target.cc',
    'mempool.cc',
    'slab_allocate.cc',
    'string.cc',
    'thread.cc',
    'thread_ctl.cc',
]

kern_defines = []


setup_sources = [
    'log_target.cc',
    'string.cc',
]

setup_defines = []


def build(x):
	kern_defines.extend(x.env.common_defines)
	setup_defines.extend(x.env.common_defines)

	x.objects(
	    target   = 'kernel_objs',
	    source   = kern_sources,
	    defines  = kern_defines,
	    use      = 'KERNEL'
	)

	if x.env.boot_multiboot:
		x.objects(
		    target   = 'mb_libs',
		    source   = ['file.cc', 'log_target.cc', 'string.cc'],
		    use      = 'MB',
		)

	x.objects(
	    target   = 'setup_objs',
	    source   = setup_sources,
	    defines  = setup_defines,
	    use      = 'SETUP'
	)

