
kern_sources = [
    'fileif.cc',
    'kout.cc',
    'string.cc'
]

kern_defines = []

def build(bld):
	kern_defines.extend(bld.env.common_defines)

	if bld.env.arch_name == 'x86_64':
		kern_defines.append('ARCH_LE')

	bld.objects(
	    target   = 'kernel_objs',
	    source   = kern_sources,
	    defines  = kern_defines,
	    use      = 'KERNEL'
	)

