#
# (C) 2012 KATO Takeshi
#

acpi_includes = [
    '#external/acpica/source/include',
]

acpi_sources = (
    'acpi_ctl.cc',
    'acpi_os.cc',
)

acpi_name = 'acpi'

def configure(x):
	if x.env['CONFIG_ACPI']:
		x.env.append_value('KERNEL_LINK_USE', acpi_name)

def build(x):
	if x.env['CONFIG_ACPI']:
		x.stlib(
		    target   = acpi_name,
		    includes = acpi_includes,
		    source   = acpi_sources,
		    use      = ['KERNEL', 'acpica_objs'],
		)

