# カーネル本体とブート処理から参照されるコード。
# コンパイルオプションが違うので別々にコンパイルする。
#
# (C) 2011-2013 KATO Takeshi
#


kern_sources = [
    'mpspec.cc',
    'pagetable.cc',
    'text_vga.cc',
]

mb_sources = [
    'pagetable.cc',
    'text_vga.cc',
]

def build(x):
	x.objects(
	    target = 'kernel_libs',
	    source = kern_sources,
	    use = 'KERNEL',
	)

	if x.env.MULTIBOOT2:
		x.objects(
		    target = 'mb_archlibs',
		    source = mb_sources,
		    use = 'MB',
		)

